# Site settings
title: Herb Home
email: hb.zhang.chn@gmail.com
description: Hi
baseurl: ""
url: "https://herbchn.github.io"

author:
  name     : 'Herb'
  email    : hb.zhang.chn@gmail.com
  url      : https://herbchn.github.io
  facebook : #
  twitter  : https://twitter.com/Herb_Kitty/

github: https://github.com/Herbchn
disqus_shortname: "herbchn"
google_analytics: UA-85435362-1

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
kramdown:
   input: GFM
permalink : /:title/
